#include "NNBirdBulletCrashEffect.h"
#include "NNAnimation.h"
#include "BHDefine.h"

NNBirdBulletCrashEffect::NNBirdBulletCrashEffect( BIRD_TYPE type )
{
	m_LifeTime = BIRD_BULLET_HIT_EFFECT_SIZE * BIRD_BULLET_HIT_EFFECT_CHANGE_SPRITE_TIME;
	m_ElapsedTime = 0;
	switch (type)
	{
	case BLACK_SMALL_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case ORANGE_SMALL_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			ORANGE_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case WHITE_SMALL_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case RED_SMALL_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case BLACK_MID_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			BLACK_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case CARAMEL_MID_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			CARAMEL_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case GREEN_MID_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case ICE_MID_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			ICE_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case YELLOW_MID_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			YELLOW_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case BROWN_BIG_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			BROWN_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case WHITE_BIG_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			WHITE_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case PINK_BIG_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			PINK_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case ITEM_KING_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			GOLD_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case RED_OLD_BIRD:
		m_Animation = NNAnimation::Create
			( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			RED_BIRD_BULLET_HIT_EFFECT_SPRITE8
			);
		break;
	case GREEN_OLD_BIRD:
	m_Animation = NNAnimation::Create
		( 
			BIRD_BULLET_HIT_EFFECT_SIZE, 
			ALL_BIRD_BULLET_HIT_EFFECT_SPRITE1,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE2,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE3,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE4,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE5,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE6,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE7,
			GREEN_BIRD_BULLET_HIT_EFFECT_SPRITE8
		);
		break;
	default:
		break;
	}

	m_Animation->SetFrameTime( BIRD_BULLET_HIT_EFFECT_CHANGE_SPRITE_TIME );
	AddChild( m_Animation );
}

NNBirdBulletCrashEffect::~NNBirdBulletCrashEffect(void)
{

}